#!/bin/bash
rm -rf origin/*
unzip "$1" -d origin
rm -rf src/autogenerated_components/*
static-html-splitter origin/index.html src/autogenerated_components react.toml
cp -r origin/{css,images,js} public
prettier src/autogenerated_components/* --write
