import React from 'react';
import Layout from './autogenerated_components/layout';
import Name from './autogenerated_components/name';
import ColumnLabel from './autogenerated_components/column_label';
import Orgname from './autogenerated_components/orgname';
import Question from './autogenerated_components/question';
import QuestionYou from './autogenerated_components/question_you';
import Response from './autogenerated_components/response';
import dummydata from './dummydata';

function App() {
  return (
    <Layout
      columns={{
        style: {
          gridTemplateColumns:
            dummydata.dates.map(() => '10vw').join(' ') + ' 42vw',
          gridTemplateRows:
            dummydata.responses.map(() => '50px').join(' ') + ' 50px 50px',
        },
      }}>
      <Orgname data-slot="orgname">{dummydata.orgname}</Orgname>
      {dummydata.dates.map(date => (
        <ColumnLabel key={date}>{date}</ColumnLabel>
      ))}
      <div></div>
      {dummydata.responses
        .map(user =>
          user.feels
            .map((feel, index) => !(user.user == "You" && feel == "?") ? <Response key={user.user + index}>{feel}</Response> : <QuestionYou/>)
            .concat(<Name key={user.user}>{user.user}</Name>),
        )
        .flat()}
    </Layout>
  );
}

export default App;
